export enum APP_TYPE {
  THIRD_PARTY = 1073741824,
}

export enum PlatformCategory {
  CONSOLE = 1,
  ARCADE = 2,
  PLATFORM = 3,
  OPERATING_SYSTEM = 4,
  PORTABLE_CONSOLE = 5,
  COMPUTER = 6,
}

export enum SteamDeckCompatibilityCategory {
  UNKNOWN = 0,
  UNSUPPORTED = 1,
  PLAYABLE = 2,
  VERIFIED = 3,
}

export enum StoreCategory {
  MULTI_PLAYER = 1,
  SINGLE_PLAYER = 2,
  CO_OP = 9,
  PARTIAL_CONTROLLER = 18,
  MMO = 20,
  ACHIEVEMENTS = 22,
  STEAM_CLOUD = 23,
  SPLIT_SCREEN = 24,
  CROSS_PLATFORM_MULTIPLAYER = 27,
  FULL_CONTROLLER = 28,
  TRADING_CARDS = 29,
  WORKSHOP = 30,
  VR_SUPPORT = 31,
  ONLINE_MULTI_PLAYER = 36,
  LOCAL_MULTI_PLAYER = 37,
  ONLINE_CO_OP = 38,
  LOCAL_CO_OP = 392,
  REMOTE_PLAY_TOGETHER = 44,
  HIGH_QUALITY_SOUNDTRACK_AUDIO = 50,
}
